### ISSUE TITLE
Decide on landing page strapline

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#175]
Multiple people from focus groups and user testing sessions have mentioned that they would like a strap line throughout the platform, while others think it would clutter the layout too much. 

This is a question for everyone:

Would you like a strapline? 
Any suggestions for straplines? 

All best, 

Georgia

**Comment by GeorgiaHCA** [comment]
Heya @jiraslama - could you add TA's feedback and your work on this to the repo? Thanks :-)

**Comment by SaimaButt** [comment]
@fjThomasStanley  to add the linked issue to the google doc ; Create an alert system where we can get feedback from the community about the strapline.

**Comment by jiraslama** [comment]
17042020
Home Page Strap Line “Creating better environments”  

How relevant is the strap Line to the project, do you feel it adds any real value?
Feedback to loose the speech marks “”.

The actual strap line was relevant and liked by Tom & Georgia. It was, discussed that this should be opened up to the community to decide on and that a, compétition should be created for the community to submit their own strap line that the community would vote on the one to use.

Additionally, for the below tagline, you may consider replacing Creating Better Environments with Creating Accessible Environments. 

 ‘Better’ is judgmental and sounds like a nice to have rather than a must have.  

Accessible, on the other hand, is more about fairness and equality and hence more implies a must have – which is hopefully what we are aiming with this project to help bring about.

**Comment by jiraslama** [comment]
01062020
Sue I Sprint 1 Feedback - Header what would you have wished to be

**Comment by jiraslama** [comment]
Sue I Sprint 1 Feedback - Header what would you have wished to be different

**Comment by jiraslama** [comment]
W
<img width="406" alt="Screen Shot 2020-07-01 at 11 31 32" src="https://user-images.githubusercontent.com/41741006/86234312-a10dae80-bb8e-11ea-990a-185591f79e7d.png">
hat would you have wished to be different

**Comment by keepingstars** [comment]
I think 'accessible' rather than 'better' is really good. It also highlights that the issue isn't just what is good but the fact that the differences are required for us to actually access or function in an environment at all.
