### ISSUE TITLE
Development training on Django

### ISSUE THREAD

**Issue by SaimaButt** [alan-turing-institute/AutisticaCitizenScience#192]

**Comment by KirstieJane** [comment]
Hi - this is mentioned as closed in #235 but I think it's right that it hasn't been closed. Can we update the issue with the purpose and requirement for it to close? I remember saying in a meeting that a summary of the training needs to be captured in the repository somewhere. That documentation serves two purposes: 1) to allow future Fujitsu team members to know what training has been completed, and 2) to help future contributors to know what skills they need to contribute to the project. I'd also like to know for project management purposes what skills have already been covered and what additional training requirements to plan for.

**Comment by fjThomasStanley** [comment]
I think this issue can be closed as the purpose of creating this specific issue was to an address an immediate concern within the Fujitsu developer team about lack of training with the Django development framework. I have created issue #249 which now specifically refers to the requirement around having documentation created of relevant training developers should undertake so that they can contribute effectively towards the project.

**Comment by SaimaButt** [comment]
As per @fjThomasStanley  comments closing the issue
