### ISSUE TITLE
Gather feedback on videos each sprint

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#204]
- [x] Define user groups who need to review and how many people
- [x] Post videos online (link to them from GitHub)
- [x] Writeprompting. questions for feedback required
- [x] Put questions publicly so they can also be reviewed
- [ ] Write explanation of the video so it can be easily followed
- [x] Add explanatory voiceover
- [x] Circulate the video to the groups who need to review it 
- [x] Link the questions to the Google form: https://bit.ly/AutisticaTuringCitSciForm so that people can it add it here for research - also give option to email 
- [x] Gather feedback iterate on that basis check metrics where possible
- [x] Add documentation so that someone else could follow the exact process

**Comment by GeorgiaHCA** [comment]
These will be for the first three sprints so that we can gather feedback on different stages. This will be useful for the following sprint planning. 

The community feedback will always be one sprint behinf the development team because they'll time to review what's been produced. You can see the process here:

https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/agile-opensource-workflow.md.

**Comment by GeorgiaHCA** [comment]
I would suggest that we try to reach the following groups, and make sure we have a mixture of genders and ages: 

* Autistic people 
     * [(A d): “I’m autistic so I’ve got an awful lot of experience which I hope to contribute to the group”](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/focus-groups/20190918_summary-18-September-2019.md#sharing-expertise-and-personal-perspective).
     * [(A g) :“We want to make it as accessible to as wide a scope of the autistic community as we can”](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/focus-groups/20190918_summary-18-September-2019.md#sharing-expertise-and-personal-perspective)
 
 * Autistic people with complex needs
 * Autistic people who are non-verbal: 
         * [(P i): “…although my son’s autistic, and he is very high-functioning there is a point where…he is very non-verbal, so I have to meet him halfway in sharing something”](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/focus-groups/20190918_summary-18-September-2019.md#communication). 
         * [(P i): “My son can’t read, write, or speak”](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/focus-groups/20191004_summary-4-October-2019.md#f-communication)

**Comment by GeorgiaHCA** [comment]
Heya @jiraslama and @pgc007 - @JamesSCTJ has kindly volunteered to lend his strategic and comms skills to help co-design the feedback process for the videos - thanks so much @JamesSCTJ ! Looking forward to working with you more.

**Comment by jiraslama** [comment]
#

**Sprints 1 – 3 Community Questions – Category Mapped Version**

| Epics / Question Categories | Questions |
|:----------:|----------|
| Platform Access | <p>What unique features would, a mentor or caregiver account need to have over a standard user account on the platform?

<br>Which kinds of devices would the platform need to support e.g. Android, iOS, Web?<br>Would the functionality of offline use be desirable e.g. would it be beneficial if you could still look at your and other's experiences without internet connection?</p> |
| Accessibility | <p>If arrows were to be, used, in platform guidance, how would their use be most beneficial?</p> |
| Site Navigation | <p>What would be the best method to navigate to different pages/areas of the platform - What would logical and clear navigation look like?</p> |
| Data Entry | <p>When submitting an experience, what would you expect to see in the following scenarios:

    - The experience is submitted to the platform successfully
    - The experience cannot be submitted to the platform due      to a technical issue such as a server problem or internet     connection issue
<br>When editing an experience that you may wish to come back to later, would you rather see a save for later button that you have to manually click in order to save a draft or the platform to autosave the edit with confirmatory text that a draft has been saved<br>When submitting an experience, what kind of input method is important to you? 
    - Free text field (unrestricted word count), 
    - Free text field (restricted word count) - If you like this method how many words would you say is suitable as a restriction?

Structured guidance: If you prefer this method, which structured prompts would you think are relevant? 

Please consider that the aim of capturing your experience is to be able to share what happened to you, how you felt as result of the experience and any suggestions that could have changed or will change the experience for the better.
    - Symbols e.g. Emoji and Widgit
    - Other - Please explain the method you would prefer
<br>How important is uploading photographs with your experience to you when submitting an experience?<br>How would you prefer to be prompted and encouraged by the platform to submit a new experience? e.g. Mobile Text Message, Email, Phone Notification, Not interested or other (If other please explain)<br>If there was, to be a confirmatory sound when you submit a new experience to the platform, what kind of sound would it be? e.g Bell, Chime, Whoosh, Not interested in a sound or other (If other please explain)</p> |
| Search | <p>If the platform were to provide a feature of showing you locations of nearby relevant sanctuaries/safe, how many sanctuaries should, be shown at once in order to provide you sufficient choice but to not be too overwhelming at the same time? e.g 1, 5, 10 or other(If other what number)<br>If the platform were to provide a feature of showing you locations of nearby sanctuaries/safe spaces, how would you like to see these presented to you? e.g. pins on a map, a list or other. Please detail what you would expect to see<br>When you want to view public experiences from others who have shared their experiences on the platform, what would be the easiest method for you to find relevant experiences? E.g. a search box, experiences plotted on a map therefore showing previously submitted experiences nearby, date and time, emotion or other. Please explain the best search mechanism and also what categories you would like to search against<br></p> |
| Community Communication | <p>What would be the best way to share community information with you? Directly in the app (If so how), Email, Newsletter, Text, Phone notification, Not interested or other. If other please explain.<br>What would be the best way to notify you when an experience is being used in a piece of research? Directly in the app (If so how), Email, Newsletter, Text, Phone notification, Not interested or other. If other please explain.</p> |

**Glossary: Site Navigation (The method and process by which a user of the platform can access different areas or pages of the platform)**
