### ISSUE TITLE
Design session for Autistica research festival

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#273]
## Summary

The Autistica research festival is being held virtually from the 3rd-10th July.  The session will be 3:30 – 4:30pm on Wednesday 8th July, held as a webinar on Zoom.

We should aim to have a rough plan for the session and autistic co-presenters arranged at least a week in advance of this. 

## Details

We will need to design a session which will be suitable for a potentially large, online audience. 
Include a substantial section for community members to speak
Make sure that the project is accesible to contributors so that we make the most of the opportunity. 

### Timing 

2-3 mins - welcome -- @KirstieJane 
10 mins - introduction to the project -- @GeorgiaHCA 
5 mins - Fujitsu involvement -- Craig
5 mins - how to contribute -- @fjThomasStanley 
10 mins - how contributions are turned into code / process documentation -- @jiraslama -- example #200 
5 mins - focus groups - Lucinda
5 mins - blog - Otis
15-20 mins - Q & A

**Comment by KirstieJane** [comment]
Thanks @GeorgiaHCA ! If folks (from Craig's email: Craig, @SaimaButt, @fjThomasStanley, @jiraslama, @georgepstaylor & @pgc007) could please comment with what they would like to see covered then I'm sure we can build an agenda 😄 

For me:

* Overview of the project, the point and the values (me or @GeorgiaHCA)
* Demonstration of how to contribute via the Google Form, YouTube videos and GitHub issues (me or @GeorgiaHCA, happy if someone else wants to speak though!)
* Examples of contributions from autistic collaborators (ideally a couple of folks would be able to showcase their own work here)
* Why and how Fujitsu contribute (from someone in Fujitsu team)
* 20 mins for Q & A so that it is interactive. There are more than 100 people signed up already so we need lots of time to answer their Qs!

**Comment by GeorgiaHCA** [comment]
I like the idea of autistic collaborators showcasing their work! That would be great. I'm also wondering how we present all the contributions that are anonymous (such as focus groups, and form responses). Maybe people could talk more generally about their input into these? It would be good to illustrate directly how they're being used.

**Comment by KirstieJane** [comment]
Yep - I think if someone who was at a focus group could talk about the experience and then maybe identify them self in the data but point out that it is anonymous enough to make them feel comfortable? Do we know anyone to ask to do that?

**Comment by SaimaButt** [comment]
Hi @GeorgiaHCA  and @KirstieJane please can you clarify the point below:

- Examples of contributions from autistic collaborators (ideally a couple of folks would be able to showcase their own work here)



@fjThomasStanley @jiraslama and I are happy to be involved for the below two points.

- Why and how Fujitsu contribute (from someone in Fujitsu team)

- 20 mins for Q & A so that it is interactive. There are more than 100 people signed up already so we need lots of time to answer their Qs!

**Comment by GeorgiaHCA** [comment]
Hi @SaimaButt - I think there's lots of options for this, including people who have co-written, reviewed, designed, and strategised for the project - so they could talk about different elements of it.

**Comment by GeorgiaHCA** [comment]
https://doi.org/10.5281/zenodo.3886557 - this is the link to the presentation we could adapt :)

**Comment by GeorgiaHCA** [comment]
Hey everyone, I've made a few actions for myself around how I need to alter the presentation:

Change cogX hash to Autistica research festival
New Zenodo link
Cut down slides by about 1/3rd to fit in with 10 mins time-frame
link to other people’s sections

I'd appreciate advice on which sections to cut, and how best to link! It'll help running through the whole session. 

Thanks!

**Comment by GeorgiaHCA** [comment]
Thank you so much for this everyone! Really brilliant work! Last thing to do before this issue closes is to upload the slides onto Zenodo and publish on the repository. @KirstieJane, do you have the Zenodo link to this?

**Comment by GeorgiaHCA** [comment]
Or I can upload it! :)

**Comment by GeorgiaHCA** [comment]
All uploaded. This was really brilliant all involved!
