### ISSUE TITLE
Accessibility -  Voice to Text

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#338]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases the voice to text feature for accessibility. The voice to text will use voice commands, have the option to listen, to commands. Voice to text will need to read the platforms copy to the user. Whilst also allowing input by voice. 

The voice to text feature will use voice commands, have the option to listen to the user, have preset commands and allow the user to create commands. 

The Voice to text will need to read the platforms copy to the user - via screen reader and turn voice input into outputted text for Where, What and How input boxes. Whilst also allowing input by voice for experiences page.

Merge voice commands and listen into voice to text feature as above.

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform

**Acceptance criteria**
Axure updated with the final UI design for the component
 A picture/screenshot image of the final UI design of the component held within Axure  
Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values
Ways of working
Data management

**Review owner:**
Internal development team
 Alan Turing

**User Feedback Labels:**
Accessibility  Voice to text 
Increasing participation

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

- A D d: “I think I would find it quite difficult to enter the experience that I just described, because I have got bad dyslexia. It would be easier for me to speak, because if I would write, it would be very different from what I just said. My spelling is quite limited, so it would be just basic words and sentences. So I could not say what I would want to say, because I would have to write down what I can spell. I would have to think about writing a simpler version, because I struggle with writing.”
- A D d: Would appreciate a voice-to-text function

**On entering text**

- d: 4x preference for text input, 1x preference for voice-to-text function
- i: 2x suggestion to offer a voice-to-text function (for other people, even though they are comfortable with entering text themselves)
- A (2) d: “I would generally be ok with this format, but I can see how some people maybe would want to just speak to describe the situation rather than having to type it all. Either because they are not so comfortable with writing or because there is a lot of nuance in the situation they are describing and they could give you that much more colour by doing it on audio. In that way you could take from it what you wish.”

**Comment by jiraslama** [comment]
https://5wwsja.axshare.com review accessibility settings features

**Comment by jiraslama** [comment]
Review accessibility panel - features by clicking on access icon which loads accessibility menu / panel 

https://5wwsja.axshare.com/#g=1&p=1-home-nav-access-settings
