### ISSUE TITLE
Accessibility - Colour Scheme Function

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#341]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases the option to change the colour scheme, for the colour scheme to include a series of pastel colours including a pinky coloured background. This will presented in a colour bar to adapt the background to the users preference. 

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform

**Acceptance Criteria**
Axure updated with the final UI design for the component 
A picture/screenshot image of the final UI design of the component held within Axure 
Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values Ways of working 
Data management

**Review owner:**
Internal development team 
Alan Turing

**User Feedback Labels:**
Accessibility 
Colour

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

- P i: Suggestion: Possibility to change the colour scheme
- A D d: “I would appreciate pastel colors, because the screen is so bright. It is probably alright, it might be just the colouring. It might be good to have a colour bar to adapt the background.”
- A D d: “As it is at the moment I would probably not use it, because I find the colours too intense.”
- A D d: Theme does not need to be a dark theme, but “just not so bright. I think more about pastel colours. I find it hard to read on. I had a test once and they gave me a kind of ‘pinky’ background, which I found easier to read on.”
- A C d: “[The contrast] is a little bit too heavy for me, but then I am short sighted, I am wearing my reading glasses. I don’t know if other people who got strong visual impairments would need that kind of contrast. I am just learning about this, that people with strong visual impairments do better with black background and yellow. So I don’t know if at any point of this ‘load up an experience’ you could have an alternative one, saying ‘do you have a visual impairment? Would you like to use this template?”

**Comment by jiraslama** [comment]
For community review 

https://k6ej5a.axshare.com/#g=1&p=1-landing-page-presentation-tech-expanded-access-o&view=b&c=1

**Comment by jiraslama** [comment]
Screen Grabs 

https://k6ej5a.axshare.com/#g=1&p=4-access-panel&view=b

![access-panel-5](https://user-images.githubusercontent.com/41741006/93070768-32150180-f677-11ea-9f93-f6355412914b.png)

**Comment by jiraslama** [comment]
<img width="585" alt="Screen Shot 2020-09-14 at 10 46 25" src="https://user-images.githubusercontent.com/41741006/93071091-91731180-f677-11ea-8543-58b36c9ad4b6.png">

**Comment by GeorgiaHCA** [comment]
This is excellent works, thanks @katoss and @jiraslama ! Perhaps for the prototype we should make a less high contrast (but not too colourful) palette as default, but make it an option for those who would prefer it - especially since some autistic users find high contrast and especially bright white backgrounds painful because of sensory processing differences.
