### ISSUE TITLE
Accessibility - New Icon

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#345]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases a set of 3 options for a new accessibility icon to provide a visual representation of the accessibility icon. This will replace the man with open arms icon. We will then seek further community feedback around the suitable choice to use for the platform from the community. The final icon will have a title to also indicate it is referring accessibility settings and be part of the proposed accessibility panel. 

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform

**Acceptance criteria**
Axure updated with the final UI design for the component 
A picture/screenshot image of the final UI design of the component held within Axure 
Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values
 Ways of working 
Data management

**Review owner:**
Internal development team 
Alan Turing

**User Feedback Labels:**
Accessibility
Accessibility Panel 
Icon

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

**Accessibility icon (man with open arms)**

- d: 2x not easy to understand
- P s: “If there is any visual accompanying the text, people will always draw conclusions, because it is faster to analyse the visuals than to read the text. So it gives you a direction. I think for ‘accessibility’ there are other signs that are more self-explanatory.”

**Comment by jiraslama** [comment]
Update to wireframe to represent the user feedback 
<img width="499" alt="Screen Shot 2020-09-09 at 11 18 00" src="https://user-images.githubusercontent.com/41741006/92586404-1502bc00-f28e-11ea-9742-057268ca71b4.png">
https://k6ej5a.axshare.com/#g=1&p=icons-accessibility-accessibility

**Comment by GeorgiaHCA** [comment]
Interesting feedback - definitely worth testing these out with the community again.

**Comment by fjThomasStanley** [comment]
Backlog refinement meeting (22/09/2020) - @GeorgiaHCA to look into including new design proposal into community newsletter

**Comment by fjThomasStanley** [comment]
Backlog refinement meeting (22/09/2020) - We will probably go with the universally accepted design: 
![image](https://user-images.githubusercontent.com/54365220/93873168-2655ba80-fcc9-11ea-9f1f-ef6a1bb678a0.png)
