### ISSUE TITLE
Experience Page Improvements - Section Titles  & New Section Other

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#350]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases a improvement to the experience page form, suggested that we remove the use of What which is used twice on the define experience and what would you like to be different input boxes. 

This will be replaced by the term How and the descriptive questioned redefined as How could this situation have been different?

Make an further box titled Other for other comments.

Define the term Where more carefully so it is less ambiguous. 

Clearly indicate and present the accessibility panel on the page so functions such as voice-to-text (speak to describe the situation, removing the need to type) can be accessed on each of the pages and not just as demoed on the home page. 

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform.

**Acceptance criteria**
Axure updated with the final UI design for the component 
A picture/screenshot image of the final UI design of the component held within Axure 
Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values 
Ways of working 
Data management

**Review owner:**
Internal development team
 Alan Turing

**Labels:**
Experience Page
Input Form
On Entering Text
Other Input Box

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

- A (2) d: “I think you don’t want the word ‘what’ to be used twice, even though they are in different sections. Because it is in different sections, I think it is ok, but I think you could probably improve it by changing the second ‘what’ maybe to ‘how’, to even make it more clear that it is a different section.
- A (2) d: “The question in the second box could be something like ‘How could this situation have been different?”

**Comment by jiraslama** [comment]
Addition of Other - Comment section to add new experience page 

https://k6ej5a.axshare.com/#g=1&p=3-enter-experience-other&view=b

Revision to support copy to Where section. The access icon - provides clearly link to the accessibility panel.
