### ISSUE TITLE
Experience Page Improvements - Section Titles  & Time / Weather

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#351]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases a improvement to the experience page in further defining what the terms, Where, What, Where mean clearly. In the Where section add time of day and the weather (Sunny, Windy, Rainy, Cold)
Make the talk about any experience in your life bolder and underneath the header text of the page.
 
**Because...**
I would like show to the wider community a Fujitsu design concept for the platform. 

**Acceptance criteria**
Axure updated with the final UI design for the component 
A picture/screenshot image of the final UI design of the component held within Axure 
Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values
Ways of working 
Data management

**Review owner:**
Internal development team 
Alan Turing

**User Feedback Labels:**
Enter Experience Page
Choice of form fields
Where

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

**Choice of form fields**

- P d: “This form gives you the impression of ‘don’t go too deep with your thoughts. Just tell very briefly, very easy to understand and follow what you think’.”
- A D d:‘Where’ and ‘What’: “It took me some time, but I would understand it eventually.”
- In relation to that: A D d: “The ‘talk about any experience in your life’ needs to be bolder, because you don’t see it right away.”
- A D d:“I suppose ‘where’ is where you live, but I am not sure.”
- A D d:“The ‘what’ - I would put my experience in there.”
- A (1) d: “For the entering experiences. I like the use of where or what. But, would it be worth adding how, why. As well as time of day - what I mean by this was weather. For e.g. sunny, windy, rainy, cold?”
- A (1) d: “I do like the layout of it and the content of the site. Maybe a field for ‘other’ would be useful, because maybe if there is something you can’t fit into the ‘Where’ or ‘What’ section, you can maybe add that to that ‘other’ part, which would be useful. I do like it overall.”
- A (2) d: “It [the choice of input fields] is pretty good, it covers the basics.”
- A (2) d: “I think you don’t want the word ‘what’ to be used twice, even though they are in different sections. Because it is in different sections, I think it is ok, but I think you could probably improve it by changing the second ‘what’ maybe to ‘how’, to even make it more clear that it is a different section.
- A (2) d: “The question in the second box could be something like ‘How could this situation have been different?”
- A (2) d: “I guess there is always more that you could add, you could add more questions, but then it gets too long for people. So I think it is ok.”
- A C d: “It is fine as long as the ‘what’ will expand itself as I type in.”
- A C d: “I think in an early version it said something like ‘Did you find your own solution?’ or ‘How did you solve it?’, but you simplified it with ‘What would you have wished to be different?’, because some people were believing that we were exchanging points of view, putting in suggestions for the people, like ‘this is how I did it’. I think that is something that we should end up exchanging [...].

**→ Overall, the form fields are understood intuitively by most participants. Some suggestions for improvement: ‘What’ should not be used twice, an ‘other’ field could be added, the ‘where’ should have an explanation so it is less ambiguous**

**Comment by katoss** [comment]
Hey, I have got a comment on adding the time of day and weather: It is true that one participant suggested this, but I think it should be discussed if this form field should be integrated or not. To me it seems like while it may be relevant for some experiences, it isn't for most (?). In any case I think it should not be a mandatory field.

**Comment by katoss** [comment]
Another idea to think about with regard to the form fields:

- Which form fields are required, which are optional?
