### ISSUE TITLE
Experience Page - Template Tab

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#354]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases a improvement to the experience page template tab, whereby when the user hovers over it a short definition as a tool tip is provided to define what the purpose of templates is - ie Template are a series of templated experience that the user can view and edit. They can also create there own templates and save them as a starting point or reference to them.

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform.

**Acceptance criteria**
Axure updated with the final UI design for the component
 A picture/screenshot image of the final UI design of the component held within Axure Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values 
Ways of working 
Data management

**Review owner:**
Internal development team
 Alan Turing

**User Feedback Labels:**
Enter Experience Page
Template Drop Down Tab

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

**‘Template’ button**

- A D d: “I am trying to work out what ‘Template’ means. I would like to have a picture of a template, so you actually see what a template is, so I don’t have to open it. Because if not, I would probably just ignore it, because I wouldn’t know what a template was if you didn’t explain it to me.”
- A (2) d: “I am not really sure what that means. It suggests to me that maybe when I am not comfortable from an accessibility standpoint with typing in all these boxes, then maybe if I click on ‘templates’ there was another format in which I could enter my experience. But I probably would not click on that, because I am quite comfortable with using the format which is right in front of me, which is just a typing box.”
- A C d: “For me no, but other people might want some prompting. But I don’t even know if I’d ever press the ‘template’.
- → We need to communicate clearer what a template is and what kind of help it offers.
