### ISSUE TITLE
Experience Page Improvements -  Accessibility

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#355]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases a improvement to the experience page with the integration of voice to text accessibility panel - and changes to make the form more accessible. Addition of text being complemented by visuals.

Make talk about any experience in your life bolder - highlight it. Add more visuals to help the core Autistic User for Where, What, How - face imaging a situation - thinking face next to it for example reference PECS or suitable icons. 

Create a hover on the Submit Media (Upload) button and make it more interactive.
Make the navy used lighter - ref royal navy, provide a series of colour swatches for royal navy for review.

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform.

**Acceptance criteria**
Axure updated with the final UI design for the component 
A picture/screenshot image of the final UI design of the component held within Axure 
Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values
 Ways of working
 Data management

**Review owner:**
Internal development team 
Alan Turing

**User Feedback Labels:**
Enter Experience Page
Interface Design
Colour
Upload

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

**The instruction “Talk about any experience in your daily life”:**

- A D d: “The question [‘Talk about any experience in your daily life’] needs to be more highlighted, because I didn’t really understand right away what information you were looking for.”

**Interface/Design**

- A D d: “The ‘talk about any experience in your life’ needs to be bolder, because you don’t see it right away.”
- P d: “This form doesn’t reflect any sort of achievements in visual representation made for autistic people, I mean, when design encourages you to think. When it is not only words, which tell you what to do and what the person is looking for, but also some visuals, like something that helps.”
- P d: “You could have a face which could indicate ‘Imagine a situation in your daily life, when some experience has happened’ and you could have a thinking face next to it. Or when you go ‘Where, what..’, you could also provide some pictures indicating location or indicating ‘experience’. On the very basic level it could be like the PECS, the picture language used for autistic people. I don’t really like PECS very much, I think they are not very attractive. But the idea is that you add more visuals rather than overload it with words.” → in the sense of “text being complemented by visuals”
- P i: “In my family, autism is high-functioning, so we don’t need serious accommodations. But we did need help with speech and all of that. But the thing is that the senses of my children are different to some extent. So for them, to get the maximum out of information, it is best when they use as many senses as they possibly can. So when you read the text, one brain area is activated, when you look at pictures, another area. If there is voice explanation, it would be a third one. The more resilient the form is, the more ‘avenues’ it uses, the better.”
- A (2) d: “I guess what is in dark blue is active.” (when inspecting the buttons ‘upload’ and ‘non-verbal’)
- A (2) d: “The upload images-function should be more within it [the input form]. Because when it is within it, it implies ‘add more specificity’ to what you have written. When it is outside, it looks like you are changing the accessibility settings of this page.”
- A C d: “The navy is just a shade too dark. It is sort of making me think: ‘What are you? You are not black, not blue. [...] If it was a shade that was more towards a royal navy, that would be better.”

**→ Apart from some smaller design issues regarding the interface, visuals or voice should be added to make the form easier accessible.**

**Comment by jiraslama** [comment]
Experience Page Updates 

Enter Negative Experience Highlighted Descriptive Sub Heading Coloured Sub Headings, Icons and Tag Type within the What (Enter your experience section) as drop down including Setting and Sensory Mapping Type. Upload & Non-Verbal features within the access panel to be considered to make the design cleaner. To be wireframed...
https://k6ej5a.axshare.com/#g=1&p=3-enter-experience-colour-icons-tag&view=b

Enter Negative Experience Highlighted Descriptive Sub Heading Coloured Sub Headings, Icons and Tag Type bottom right. 
https://k6ej5a.axshare.com/#g=1&p=3-enter-experience-negative-highlighted-tag&view=b

Enter Experience Colour Sub Headings, Icons with Tags Categories within the What (Enter your experience section)
https://k6ej5a.axshare.com/#g=1&p=3-enter-experience-highlighted-tag&view=b

Enter Experience Speech Bubble Sub Headings, Heading Tab Emoji Icons with Tags Setting / Sensory Mapping Drop Down within What (Enter Experience) Section. 
https://k6ej5a.axshare.com/#g=1&p=3-enter-experience-bubbles&view=b

**Comment by jiraslama** [comment]
Experience Page Justifications - Review

Integration of voice to text accessibility panel via access icon as shown

Consideration to add Upload and Non-Verbal to the access panel

Form accessibility improved by adding text complemented by visuals - suitable icons
to help the core Autistic User

Make talk about any experience in your life bolder by highlighting it as wireframe

Data Storage Icon which was not liked replaced with Thinking icon option 1 and Person thinking option 2 with person and bubble icon

Icons for negative experience and how would you have wished for the experience to be 
different added to given section tabs as feedback number of versions for review

Icon consider to represent both negative and positive experience half smiley / half unhappy face

Icons explored and also added for:
Where, What, How - face imaging a situation explored PECS and previous Mulberry sets 
in favour of chosen generic icons. Speech bubbles with section title also explored as demos.

In ref to use of dark blue named navy - request to make the navy used lighter - as ref to royal navy colour swatch and other series of blue colour swatches explored and shown as link https://k6ej5a.axshare.com/#g=1&p=navy-blue - gain community feedback. 

Create a hover on the Submit Media (Upload) and non-verbal buttons with a suitable icon and make it more interactive, drop down shadow hoover and click interactivity added to these two buttons.
