### ISSUE TITLE
Short Description  -  Rating Scale

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#356]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases feedback received on the rating scale used within the short description feature. 

Need to define location within short description feature and only negative experiences. 
Use scale 3 to 10 non-binary if this scale is used. 

Clearly state the user is defining only negative experiences. 
Add description to 5 stars - for example 1 (not good)  - 5 (terrible) 
Stars preferred over the emojis - Replace 5 stars with 5 hearts for the ratings. 
Consider the scale used for pro health as ref.
 
Add words to provide a explanation of the scale of the negative experience.
Consider sourcing a series of icons to represent the severity of how challenging or difficult a experience was.

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform.

**Acceptance criteria**
Axure updated with the final UI design for the component
 A picture/screenshot image of the final UI design of the component held within Axure Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values
 Ways of working
 Data management

**Review owner:**
Internal development team
 Alan Turing

**User Feedback Labels:**
Enter Experience Page
Short Description
Rating Scale

**Comment by SaimaButt** [comment]
Linked to #261

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

**Labels/Number of choices**

- A D d: would prefer 3 smileys (there would be too much choice if there were more options)
- A (1) d: “Rating scales would be useful to have some comparison to. As well as, give each star or emoticon a brief label or description.”
- A (1) d: “I’d say I would prefer 5 options. If there was a description of what the stars mean, that could be very useful. But I like the idea.”
- A (1) d: If you add explanations, like 1 being ‘not good’ and 5 being the highest, that would help. I like the idea.”
- A (2) d: “I think these binary options with two or three choices are not enough. You won’t get accurate feedback, the data is going to be too skewed. It is like ‘Was it a good or bad girlfriend? I don’t know, we split up, but the experience I had was great, I think she was great, but it just didn’t work out.’. So I think you need to have something with more choices, like 1 out of 10 or something. But even then, like, if you had 5 options, how would you rate it? It could still be problematic, because if I wrote a negative experience, what is the type of the negative experience? Am I rating ‘was it a 1 negative or a 5 negative?’. You would need to be clearer. What I sometimes see in surveys, what I think is pretty good, it says like ‘1 to 10’ and then it has words to explain what it means, like 5 is ‘normal’ and 10 is ‘positive’. It has some words to describe what each rating would mean, in the direction of good or bad. So, I think you would need more choices and also some words to explain, what those mean as well.”
- A (2) d: “There are some good examples of ratings that I have used, they are vaguely in my head. I know it was still hard to decide whether it is a 7 or a 9, because it is a subjective decision, but at least it was clear how the rating system works. I would say that you should keep looking for a better rating system.”

**→ Preference for number of rating options varies from 3 to 10. 2 is tendentially seen as too binary.**

**Emojis**

- A (1) d: “I like the idea of using the emojis. I like the one with three emojis a lot, because I think it is simple, but effective to use to get that kind of feedback.”
- A C d: “Smileys personally, I don’t like them.”
- A D d: preference for smileys

**Stars**

- A (1) d: “I think the stars would be useful, I like the stars. If you add explanations, like 1 being ‘not good’ and 5 being the highest, that would help. I like the idea.”
- A (1) d: “I think I prefer the stars over the emojis.”
- A (1) d: “For the stars, I think if you write next to add that 1 is the lowest and 5 is the highest option, I don’t know if all people would be able to or would like to use it in that way. So I think the emojis might be the better option.”
- A C d: “Stars are fine.”

**Happy/sad/good/bad locations**

- P d: “I think it depends on the data you would like to collect, because when we talk about ‘good location’ that would probably mean ‘it was alright, nothing went wrong’. A ‘happy location’ would probably be something where people went beyond usual expectations and there was something thoughtful that made you smile. So for me ‘good’ and ‘happy’ are different. But I think it needs some guidance on what you mean exactly. Some places look nice, but they are just not good for us. I wouldn’t call that a bad location.”
- A D d: ‘good locations’: “I don’t know what the one with the tick and the cross mean.”
- A C d: “Happy locations, good locations, sad locations...I’d just put unhappy, I think unhappy looks like it is something that can be changed, sad looks like it is always going to be sad.”
- A C d: “I don’t think I would even put ‘bad locations’, because it feels like underscoring. I’d just have the two positives and one negative one.”
- A C d: “The location tag is familiar.”

**Other scales**

- Suggestion of stars with emoji faces (by moderator):
- A (1) d: “would also be an idea”
- A C d: “I don’t like the thermometer, because it makes me think of medical things.”
- A (1) d: “Temperature (was this a cold or hot situation).”
- A C d: “No for ‘thumbs up’ and ‘thumbs down’. It feels slightly overused. I personally don’t like it.”
- A C d: “I don’t know why to bother with the negative one, I would just have the heart. Maybe you could substitute the number of hearts with the number of stars.”
- 5-star rating but with hearts (suggestion by moderator):
- A C d: “Yes I think you could do that easily and it would look quite nice, because it is not rating what you are eating, but it is rating your experience.”
- A (2) d: Suggestion for a scale (emojis with labels): https://www.prohealth.com/library/what-the-pain-scale-really-means-34982
- A (1) d: “Tick/cross selection?, For examples thumbs up, thumbs down.”

**Rating history**

- A (2) d: “Rating scale – have a history or record of it of how it compares e.g. data or graph, bar chart, pie chart?”

**→ The suggestion of having the option to rate experiences was generally appreciated. The design of the scale needs to be discussed.**
