### ISSUE TITLE
Experience Views -  Re-Design Related to Toggle View  & Views

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#357]
**As a Fujitsu developer**

**I would like**
A wireframe design and justification that showcases feedback received on the experience page - changes to the view button, term view as a title,  view toggle design and actual views themselves.

Relabel view button title to - view all of my submissions or viewing history. 
Build out experience viewer with actual experiences from the community. 
Add gridlines and format list format view adding space to column headings more inline with current table views use of colour- make both views clearer. 
Make list view clearer, include ratings in the views. 

Improve view toggle design by adding list view and table view. 
Add tool tip to the term Toggle to aid clarity 
Define the purpose of the views in a description under the page header title. 

**Because...**
I would like show to the wider community a Fujitsu design concept for the platform.

**Acceptance criteria**
Axure updated with the final UI design for the component 
A picture/screenshot image of the final UI design of the component held within Axure Justification of the component design available in Github repository as an .md file

**Other relevant documents:**
Values 
Ways of working 
Data management

**Review owner:**
Internal development team 
Alan Turing

**User Feedback Labels:**
Experience Viewer
Toggle View
List View
Table View

**Comment by katoss** [comment]
# Original user testing feedback

From https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/community-recommendations/user-tests/sprint-6-feedback/summary-sprint6-feedback.md

**Views-button (on ‘enter experience’ page)**

- **The label ‘views’ is confusing for some participants. Their interpretation of the meaning of the views-button:**

- P d: “Maybe other people’s views”
- A (1) d: “Other views [experiences] from other users.”
- A (2) d: “It is probably just, if I want this screen to visually look a little bit different, maybe in a different format that would be a little more pleasing, less stimulating or more appropriate for me, while keeping the same content. Or it might mean ‘View all of my responses from before’, so ‘view’ like ‘everything I have written’. But I think it is probably the former.”
- A (2) d: “I don’t know if that word, ‘views’, is the right word, even though I guessed it.”
- A (2) d: “Intuitively, I don’t think there is a great word to put there that everyone will understand, but I could look around. It is not a common feature of websites that you can go back to your complete log, but there has got to be some example out there.”
- A C d: “Whether it is viewable by others?”
- A C d: Suggestion for relabelling of ‘views’ button to make it clearer: ‘viewing history’

**→ ‘Views’ button should be relabelled.**

**Views page
List view**

- P d: “This is your feed from the website. So basically what other people said. It is not very exciting to see it this way. But I guess for people who work with it it is fine. I mean, for me, I probably would not go through it out of interest.”
- P d: It is confusing that there is no text under some of the “What would you have liked to be different?” questions:
- confusing, looks like you invite someone to comment
- “If there is no input, there should be something saying ‘no information’”
- A (2) d: “Having something in list form is great, and you have that, which is good. I just think the actual formatting could be a little more distinguished.”
- A (2) d: “The list format is a little bit unclear, because it doesn’t have any gridlines, so I think the list could be a bit more formatted with a little bit more boxes and underlines and so on. It looks a lot like a lot of words smushed together for me. Obviously, there was an effort made to distinguish, by using colours, but it is unlike the table, which is just a little more clean.”

**Table view**

- A (1) d: “I think it is a template of someone to express overall how their experiences were, like on a daily basis.”
- A (1) d: “Initially, when I looked at it, I would have had the idea to fill it in, but I think it was understood from my part.”
- A (1) d: “I do like it, but as you write, will the grid bend? When you put in the text, this could be altered or changed.”
- A (2) d: “[...] unlike the table, which is just a little more clean [than the list format].”
- A (2) d: “ I think the details of the table look pretty well laid out.”
- A C d: “I don’t like anything cellular.[...] It is mathematical to me. Other people may like it, and therefore enter one word and they like that. So I would just write ‘Do you like words or do you like cells to enter your experiences?’.”

**Preferred view**

- P d: Preference of table or list view depends on the use case
- A (2) d: “I think having options is good, I think the details of the table look pretty well laid out. The list format is a little bit unclear, because it doesn’t have any gridlines, so I think the list could be a bit more formatted with a little bit more boxes and underlines and so on. It looks a lot like a lot of words smushed together for me. Obviously, there was an effort made to distinguish, by using colours, but it is unlike the table, which is just a little more clean.”
- A C d: “I don’t like anything cellular.[...] It is mathematical to me. Other people may like it, and therefore enter one word and they like that. So I would just write ‘Do you like words or do you like cells to enter your experiences?’.”
- A (1) d: “I overall liked the list and table view. But I would like to expand it. What I saw in a nice way was: nice colours, it was warm. The text was nice, it wasn’t too big or too harsh. I think the use of a rating, like emojis or stars would be nice to further express the event or experience.”

**→ The users generally liked having the option to toggle between views, even though personal preference varied. The simple design is mostly seen as ok, but could be improved.**

**Toggle**

- A (2) d: “I think generally it is good that you are giving people several options. I think that the toggle is pretty clear. I think that the words ‘table’ and ‘list’ are pretty clear. I think ‘table’ and ‘list’ is quite clean, but you might change it to ‘list view’ and ‘table view’. Just adding the word ‘view’ might make it a lot more clear what the toggle on top is giving you a choice of. The word toggle is there on the left, so it is already implied, although then it becomes a little bit awkward, because here is the word ‘view toggle’. You could remove ‘view’ from there and then add it to ‘table view’ or ‘list view’.”
- A C d: “What does ‘view toggle’ mean?”

**Colours**

- A C d: “I would say that the blue on this is right. Maybe slightly darker. If you use this in the background of the input form, then I think you’re doing ok.”

**General remarks**

- P d:“If the experiences of other people were in the same place where I enter my experiences, I might be interested to read. It is almost like a restaurant review. You would want to read the comments to see whether other people think the same. Or before you go it would be interesting to read the comments to see what to expect and to decide whether you want to go or not. So I think it is almost like a rating for the place.”
- A (1) d: “To understand the context of the experiences, having a scale there, from 1 to 5 or emoticons, would that be something to consider?”
- A (1) d:“I like it, but I would like to have a symbol to represent the severity of how challenging or difficult it was. It could be by stars or emoji faces. This would give more depth and meaning. Otherwise I think it is ok. Apart from that, I would like an ‘other’ section.”

**Comment by katoss** [comment]
Another idea to think about with regard to the display of own/other's experiences:

- What are the target groups and use cases for the different views?
