### ISSUE TITLE
Draft stories for moderation testing of the Code of Conduct

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutisticaCitizenScience#513]
## Summary

One key way to test our code of conduct and moderation process will be to test it against example stories to ensure that the code of conduct is understood and clear. 

Our testing will be asking volunteers to read our code of conduct and assess example stories as to whether they are appropriate or not. 

Stories are to be in scope of the project:
- How **_sensory processes_** have been impacted by public environments

## Date Due by

30/07/21

## Suggestions for tasks that can fix this issue

* [ ] Draft stories in a google document
* [ ] Send for review by copy and pasting the link in a comment in this issue

## Who can help

Anyone who is interested in moderation and creating stories.

**Comment by skfantoni** [comment]
I can write up some stories today if you want. Shall I start the google doc or do you already have one?

**Comment by skfantoni** [comment]
Can I just clarify, are we including vestibular and proprioception differences in our definition of sensory differences?

**Comment by lottycoupat** [comment]
@skfantoni I haven't started a google doc - so if you want to start one please do and share it 😄 

In regards to that second question, I'm not sure - @GeorgiaHCA can you advise on this?

**Comment by GeorgiaHCA** [comment]
Hiya @skfantoni, yes absolutetly, I think that's important! Very good qusetion. Lots of issues like dyspraxia (relating to proprioception) which are co-occurent with autism and enormously impact navigating environments. Also nociception, I believe, is explicitly mentioned in DSM-5, although I'm not suggesting DSM should give the ultimate mandate!

**Comment by GeorgiaHCA** [comment]
You have made me think @skfantoni that we need to be much more broad and explicit about what is in the category of sensory processing, so people are encouraged to write about that kind of experience. It's part of the tricky issue again of not imposing categories so that people's experiences can emerge, but also having a useful focus for the research. Do you have any suggestions to phrase it for autism comms? For me, the dream would be some text about sensory processing differences that:

1) Emphasises sensory process is the **focus** of the research 
2) Makes clear sensory processing can involve more than the classic '5 senses', including things such as balance, pain, temperature 
3) Be clear to a diverse range of inividuals, including people who may have learning differences or not appreciate verbose jargony language 
4) Leaves scope for people to inform us that our sensory categories may need adjusting, from their own live experiences 
5) Isn't too long

**Comment by skfantoni** [comment]
This is the [link](https://www.autism.org.uk/advice-and-guidance/topics/sensory-differences/sensory-differences/all-audiences#:~:text=Processing%20everyday%20sensory%20information%20can,effect%20on%20a%20person's%20life.) I shared with Lottie and James when we met up last week.

When I first got diagnosed I avoided Googling as I didn't want become obsessive but this article helped me make sense of so much.

**Comment by skfantoni** [comment]
[Draft Stories so far](https://docs.google.com/document/d/1N0cG5M51dmdWm2g5eS8IVcOrjlaZVIBskjAmw0o-J2c/edit?usp=sharing), figured I'd write some that are all good, some that are debatable and some that are definitely red. Admittedly, I'm not sure how to write offensively so we may need someone less autistic to do that lol.

**Comment by skfantoni** [comment]
I'm going to move this over to issue with #514 in order to keep things compact and easier to track :)
