### ISSUE TITLE
Link to Fujitsu work on main repo

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#85]
Show the work that the Fujitsu has been doing on the main repo or link to it via. Pull requests and issues so Georgia and Kirstie can take a look :) Thank youuu!!!!

**Comment by EllenDevereux** [comment]
Pull request to README file to say something about Fujitsu's involvement
Assignee - Thomas
Milestone - Reporting and accountability
Labels - high, Fujitsu

**Comment by EllenDevereux** [comment]
@fjThomasStanley please can you follow up on this? (Georgia & chris are going to go through this which may close this issue)

**Comment by EllenDevereux** [comment]
@fjThomasStanley please can you create a pull request from FJ fork to main repo of the file on FJ involvement. Thanks :)

**Comment by fjThomasStanley** [comment]
Created pull request #178 to merge fjAutisticaCitizenScience[Master] fork with the main Alan Turing[Master] repo

**Comment by SaimaButt** [comment]
@fjThomasStanley do you remember why this was sent back to us?

**Comment by fjThomasStanley** [comment]
@SaimaButt PR #178 originally contained changes to include Angular based source code, and this PR was fairly hefty because of this. The master branch on the fjautisticacitizenscience fork has since been updated to remove the Angular code, but now should be reviewed again. The current state of the master branch still has quite a lot of changes, however this is because most of the additional files are images that Chris needed to support the community questions piece of work

**Comment by GeorgiaHCA** [comment]
I am closing this issue since we are now in a new phase of development. Thank you everyone for your work! ⭐
